# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RMovie
	
	pod 'Alamofire', '~> 4.0'
	pod 'RAMAnimatedTabBarController', "~> 2.0.13"
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
	pod ‘Shimmer’
	pod 'BetterSegmentedControl', '~> 0.7'
	pod 'SDWebImage', '~>3.8'
	pod 'SwiftHEXColors'
	pod "XCDYouTubeKit", "~> 2.5"
	pod 'SwiftyJSON'
	pod 'NVActivityIndicatorView'
	pod 'EZYGradientView', :git => 'https://github.com/Niphery/EZYGradientView'

end
